### ISSUE TITLE
missing keys during loading changed language

### ISSUE THREAD

**Issue by melounek** [i18next/i18next-xhr-backend#266]
I made the example of the issue here: https://www.webpackbin.com/bins/-KuxsDAcwJ2azm0S41y-
Here on the first `changeLanguage()` I write to the console `t('title')` right after changing the language and it returns me "missing key error"

I understand it's not a big deal in some Apps, but If I am using `react + redux + redux-form...` and my App rerenders on every change. This causes a problem, because it displays constants (or fallbackLng) during the loading a resorce which look bad.

Maybe it would be possible to avoid rerendering before finishing  'changeLnaguage()', but I think It would be better if the `t()` function will return the last valid translate instead of "missing key" during the resource loading.

**Comment by jamuhl** [comment]
did you check the wait flag?!?

https://react.i18next.com/components/translate-hoc.html#a-set-those-on-i18next-init

could be set global or on each translate hoc in options....

**Comment by melounek** [comment]
Yes, it's set correctly, but it doesn't have influence on this, because, right after the change if something outside of `changeLanguage()` starts rerender (like redux in my case) it will cause this issue.

**Comment by jamuhl** [comment]
see https://www.webpackbin.com/bins/-Kuy3hMrmOV_AtODlLx8

update react-i18next version to v5.4.1 and added bind to options.init:

```
react: {
      wait: true,
      bindStore: false,
      bindI18n: 'languageChanged'
    }
```

does the trick

**Comment by melounek** [comment]
If I put the line right after changeLanguage, it's still throwing the error on first change: https://www.webpackbin.com/bins/-Kuy76Jxfi1OZtv3S61N

**Comment by jamuhl** [comment]
move that to callback and your save `changeLanguage(lng, () => { console.log ... });`

As all access to t should be in render there should be no issue with missings - even more as missing does try to fallback to `en` if you do not uncomment that `fallbackLng` in init of i18next.

**Comment by jamuhl** [comment]
Hm...we might have to take a step back...were do you see an issue...?

**Comment by melounek** [comment]
I understand the callback that this can be the way, but not for a "react-redux thinking person" because I want to change the global state of language, so it will rerender components and triggers changeLanguage() in one moment (not changeLanguage and update the state in callback like you are recommending)

fallbackLng will avoid to throwing missingKey errors but if I am changing de=>es it will display mi for a second english translate, which is not good at all.

So I think the issue is, during loading a new language resource, `t()` function should be returning the last used translate. So maybe property `i18n.language` should be changed after `changeLanguage()` loads the resource.

Because one never know when the app will be rerendered and when it will ask for `t()`

**Comment by jamuhl** [comment]
fallbackLng will avoid to throwing missingKey errors but if I am changing de=>es it will display mi for a second english translate, which is not good at all.

=> why? a rerender is just triggered after languageChange is done (using those bind options correctly and latest react-i18next) - so there won't be a wrong render of the fallback value - it's just when you do a console.log inside your function - nothing todo with real code

regarding redux...we're heavy users of redux in big business applications. We use an action to trigger language change and from there call changeLanguage in a redux-saga.

Because one never know when the app will be rerendered and when it will ask for t()

=> We know when a rerender gets triggered with new language -> that's what the hoc is there for

**Comment by melounek** [comment]
So that means one cannot change the redux global state (causing rerender) and changeLanguage in one moment? If yes, I can handle it, but maybe this should be mentioned in documentation.

**Comment by jamuhl** [comment]
What global state change?...how can a redux state change be in same moment (single thread) as a changeLanguage triggered by user input? Sorry but i'm too slow to get the point - do you see a performance issue on one render caused by a user triggering change language once?

Or you got an issue with the setState caused by the missing? Those should be translated or at least in fallback lng before going to production...

**Comment by jamuhl** [comment]
Anyway...seems i do not really get the root of your problem...do you mind to make a PR to improve react-i18next (seems not related to the xhr-backend) to be useful for your case?

**Comment by melounek** [comment]
I want to do it in same moment, because I am triggering `changeLanguage()` inside the `store.subscribe()` based on language in the store changes.

Or the same effect can be simulated by this code snippet (if I don't use the callback)
```
  handleLangChange = value => {
    this.props.dispatch(setLoginData({ lang: value.target.value }))
    this.props.i18n.changeLanguage(value.target.value)
  }
```

> do you mind to make a PR to improve react-i18next

More looks like this is related directly to i18next ... but you are right this "issue/behavior" will be probably same for all backends, so I will try to find the time to report that higher.

Thanks for feedback.

**Comment by jamuhl** [comment]
Not sure but does not look like an i18next problem/issue in general. It's very specific to using react - redux.

Do you reduce the setLoginData action? And are views connected to that store change? If so why you use that lang value in a view? No connect to that state - no rerender...

Anyway...looking forward to your PR. Thank you.

**Comment by melounek** [comment]
https://github.com/i18next/i18next/issues/968
