### ISSUE TITLE
Why does zh/translation.json automatically load

### ISSUE THREAD

**Issue by bihongbin3027** [i18next/i18next-xhr-backend#367]
![image](https://github.com/i18next/i18next-xhr-backend/assets/15045200/91a59af3-7842-4136-8b77-6af4442d529f)
![image](https://github.com/i18next/i18next-xhr-backend/assets/15045200/563a1a68-5801-4276-83e2-e990f055ddb3)
![image](https://github.com/i18next/i18next-xhr-backend/assets/15045200/5525312d-087b-440f-899d-414b9574f4d4)

**Comment by bihongbin3027** [comment]
Why does the zh/translation.json file automatically load? I haven't even defined the zh folder.

**Comment by bihongbin3027** [comment]
![image](https://github.com/i18next/i18next-xhr-backend/assets/15045200/49344e9d-eff8-4fb3-bc80-4f41c532caa8)

**Comment by adrai** [comment]
because of the default option: `load: 'all'`

<img width="755" alt="image" src="https://github.com/i18next/i18next-xhr-backend/assets/1086194/89cbd907-12ff-41f1-ab6d-a742c8f9c0a8">

Try to set it to `load: 'currentOnly'`

https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

btw: i18next-xhr-backend is deprecated... use i18next-http-backend instead

**Comment by bihongbin3027** [comment]
thanks. @adrai
